name: DownloadMapPreviewImagesMapPingJSON

concurrency:
  group: prevent-stuck-run
  cancel-in-progress: true

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 */14 * *'  # 每 14 天触发一次

jobs:
  DownloadMapPreviewImagesMapPingJSON:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v3
      with:
        ref: master

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow tqdm

    - name: 运行脚本
      timeout-minutes: 10
      id: check_script
      run: |
        python scripts/DownloadPreviewImagesByMappingJson.py cs2/counterstrikesharp/configs/plugins/MapChooser/MapPing.json

    - name: 压缩 map_previews_images 文件夹
      if: always()  # 即使脚本出错也执行此步骤
      run: |
        zip -r map_previews_images.zip map_previews_images
      working-directory: ./

    - name: 上传压缩文件作为 Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: map_previews_images
        path: map_previews_images.zip
        

    - name: 上传压缩文件到UPKK远程服务器
      timeout-minutes: 5
      run: |
        RESPONSE=$(curl --max-time 60 --connect-timeout 10 -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "token=${{ secrets.SECRET_TOKEN }}" \
          -F "file=@map_previews_images.zip" \
          https://bbs.upkk.com/plugin.php?id=xnet_core_api:GithubAction_map_previews_images)

        echo "Server Response: $RESPONSE"

        STATUS=$(echo "$RESPONSE" | jq -r '.status')
        MESSAGE=$(echo "$RESPONSE" | jq -r '.message')

        if [ "$STATUS" != "success" ] || [ "$MESSAGE" != "File uploaded and extracted successfully." ]; then
          echo "Upload failed or unexpected response from server."
          exit 1
        fi

        echo "Upload and extraction succeeded."
