name: Validate JSON and JSONC files

on:
  push:
    paths:
      - 'cs2/counterstrikesharp/configs/map-text/**' # 监视此目录中的所有变化
      - 'cs2/entwatch/maps/**'
      - 'cs2/counterstrikesharp/configs/weapons_buyCommand/weapons.json' # 监视特定文件
      - 'cs2/cs2fixes/configs/zr/playerclass.jsonc'
      - 'cs2/counterstrikesharp/configs/plugins/Advertisement/Advertisement.json'
  pull_request:
    paths:
      - 'cs2/counterstrikesharp/configs/map-text/**' # 监视此目录中的所有变化
      - 'cs2/entwatch/maps/**'
      - 'cs2/counterstrikesharp/configs/weapons_buyCommand/weapons.json'
      - 'cs2/cs2fixes/configs/zr/playerclass.jsonc'
      - 'cs2/counterstrikesharp/configs/plugins/Advertisement/Advertisement.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List changed files
      id: list_changed_files
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Install jsonc-parser
      run: npm install jsonc-parser

    - name: Create JSONC validation script
      run: |
        echo "const fs = require('fs');" > validate-jsonc.js
        echo "const { parse } = require('jsonc-parser');" >> validate-jsonc.js
        echo "const filePath = process.argv[2];" >> validate-jsonc.js
        echo "const content = fs.readFileSync(filePath, 'utf8');" >> validate-jsonc.js
        echo "try {" >> validate-jsonc.js
        echo "  parse(content);" >> validate-jsonc.js
        echo "  console.log('Valid JSONC:', filePath);" >> validate-jsonc.js
        echo "} catch (error) {" >> validate-jsonc.js
        echo "  console.error('Invalid JSONC:', filePath);" >> validate-jsonc.js
        echo "  console.error(error.message);" >> validate-jsonc.js
        echo "  process.exit(1);" >> validate-jsonc.js
        echo "}" >> validate-jsonc.js

    - name: Validate JSON and JSONC files
      run: |
        echo "Validating JSON and JSONC files..."
        while IFS= read -r file; do
          if [[ $file == *.json || $file == *.jsonc ]]; then
            echo "Validating $file"
            if [[ $file == *.json ]]; then
              npx jsonlint-cli "$file" || exit 1
            elif [[ $file == *.jsonc ]]; then
              node validate-jsonc.js "$file" || exit 1
            fi
          fi
        done < changed_files.txt
        
